[workspace]
members = [
    "programs/*"
]

[profile.release]
overflow-checks = true
codegen-units = 1
strip = true
opt-level = "z"
lto = true
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
