export enum JoypadButton {
  Nothing = "DO NOTHING",
  Up = "↑",
  Down = "↓",
  Left = "←",
  Right = "→",
  TurboUp = "Turbo ↑",
  TurboDown = "Turbo ↓",
  TurboLeft = "Turbo ←",
  TurboRight = "Turbo →",
  A = "A",
  B = "B",
  Start = "START",
  Select = "SELECT",
}
