// https://datacrystal.romhacking.net/wiki/Pok%C3%A9mon_Red/Blue:RAM_map

export const GAMEBOY_MEMORY_OFFSET = 0x8000;

export const LETTER_PRINTING_DELAY_FLAGS_LOCATION = 0xd358;

// Pokemon 1, use as starting point for all pokemon
export const POKEMON_1_NAME = 0xd16b;
export const POKEMON_1_NICKNAME_START = 0xd2b5;
export const POKEMON_1_HP_START = 0xd16c;
export const POKEMON_1_MAX_HP_START = 0xd18d;
export const POKEMON_1_LEVEL = 0xd18c;

// Pokemon data offsets
export const POKEMON_HP_SIZE = 2;
export const POKEMON_NICKNAME_SIZE = 11;
export const POKEMON_SIZE = 44;

// https://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_index_number_(Generation_I)
export const POKEMON_INDEX = [
  null,
  "RHYDON",
  "KANGASKHAN",
  "NIDORAN♂",
  "CLEFAIRY",
  "SPEAROW",
  "VOLTORB",
  "NIDOKING",
  "SLOWBRO",
  "IVYSAUR",
  "EXEGGUTOR",
  "LICKITUNG",
  "EXEGGCUTE",
  "GRIMER",
  "GENGAR",
  "NIDORAN♀",
  "NIDOQUEEN",
  "CUBONE",
  "RHYHORN",
  "LAPRAS",
  "ARCANINE",
  "MEW",
  "GYARADOS",
  "SHELLDER",
  "TENTACOOL",
  "GASTLY",
  "SCYTHER",
  "STARYU",
  "BLASTOISE",
  "PINSIR",
  "TANGELA",
  null,
  null,
  "GROWLITHE",
  "ONIX",
  "FEAROW",
  "PIDGEY",
  "SLOWPOKE",
  "KADABRA",
  "GRAVELER",
  "CHANSEY",
  "MACHOKE",
  "MR. MIME",
  "HITMONLEE",
  "HITMONCHAN",
  "ARBOK",
  "PARASECT",
  "PSYDUCK",
  "DROWZEE",
  "GOLEM",
  null,
  "MAGMAR",
  null,
  "ELECTABUZZ",
  "MAGNETON",
  "KOFFING",
  null,
  "MANKEY",
  "SEEL",
  "DIGLETT",
  "TAUROS",
  null,
  null,
  null,
  "FARFETCH'D",
  "VENONAT",
  "DRAGONITE",
  null,
  null,
  null,
  "DODUO",
  "POLIWAG",
  "JYNX",
  "MOLTRES",
  "ARTICUNO",
  "ZAPDOS",
  "DITTO",
  "MEOWTH",
  "KRABBY",
  null,
  null,
  null,
  "VULPIX",
  "NINETALES",
  "PIKACHU",
  "RAICHU",
  null,
  null,
  "DRATINI",
  "DRAGONAIR",
  "KABUTO",
  "KABUTOPS",
  "HORSEA",
  "SEADRA",
  null,
  null,
  "SANDSHREW",
  "SANDSLASH",
  "OMANYTE",
  "OMASTAR",
  "JIGGLYPUFF",
  "WIGGLYTUFF",
  "EEVEE",
  "FLAREON",
  "JOLTEON",
  "VAPOREON",
  "MACHOP",
  "ZUBAT",
  "EKANS",
  "PARAS",
  "POLIWHIRL",
  "POLIWRATH",
  "WEEDLE",
  "KAKUNA",
  "BEEDRILL",
  null,
  "DODRIO",
  "PRIMEAPE",
  "DUGTRIO",
  "VENOMOTH",
  "DEWGONG",
  null,
  null,
  "CATERPIE",
  "METAPOD",
  "BUTTERFREE",
  "MACHAMP",
  null,
  "GOLDUCK",
  "HYPNO",
  "GOLBAT",
  "MEWTWO",
  "SNORLAX",
  "MAGIKARP",
  null,
  null,
  "MUK",
  null,
  "KINGLER",
  "CLOYSTER",
  null,
  "ELECTRODE",
  "CLEFABLE",
  "WEEZING",
  "PERSIAN",
  "MAROWAK",
  null,
  "HAUNTER",
  "ABRA",
  "ALAKAZAM",
  "PIDGEOTTO",
  "PIDGEOT",
  "STARMIE",
  "BULBASAUR",
  "VENUSAUR",
  "TENTACRUEL",
  null,
  "GOLDEEN",
  "SEAKING",
  null,
  null,
  null,
  null,
  "PONYTA",
  "RAPIDASH",
  "RATTATA",
  "RATICATE",
  "NIDORINO",
  "NIDORINA",
  "GEODUDE",
  "PORYGON",
  "AERODACTYL",
  null,
  "MAGNEMITE",
  null,
  null,
  "CHARMANDER",
  "SQUIRTLE",
  "CHARMELEON",
  "WARTORTLE",
  "CHARIZARD",
  null,
  null,
  null,
  null,
  "ODDISH",
  "GLOOM",
  "VILEPLUME",
  "BELLSPROUT",
  "WEEPINBELL",
  "VICTREEBEL",
];

// https://bulbapedia.bulbagarden.net/wiki/Character_encoding_(Generation_I)
const CHARCTER_ENCODING = [
  ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],

  ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],

  ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],

  ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],

  ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],

  ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],

  [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "V",
    "S",
    "L",
    "M",
    ":",
    "ぃ",
    "ぅ",
  ],

  ["‘", "’", "“", "”", "・", "⋯", "ぁ", "ぇ", "ぉ", "", "", "", "", "", "", ""],

  [
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
  ],

  [
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "(",
    ")",
    ":",
    ";",
    "[",
    "]",
  ],

  [
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
  ],

  [
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "é",
    "'d",
    "'l",
    "'s",
    "'t",
    "'v",
  ],

  ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],

  ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],

  [
    "'",
    "PK",
    "MN",
    "-",
    "'r",
    "'m",
    "?",
    "!",
    ".",
    "ァ",
    "ゥ",
    "ェ",
    "▷",
    "▶",
    "▼",
    "♂",
  ],

  [
    "$",
    "×",
    ".",
    "/",
    ",",
    "♀",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
  ],
];
export const memorySliceToString = (memorySlice: Uint8Array) => {
  const charArray = [];
  for (let i = 0; i < memorySlice.length; i++) {
    const firstNibble = (memorySlice[i] & 0xf0) >> 4;
    const secondNibble = memorySlice[i] & 0xf;
    const char = CHARCTER_ENCODING[firstNibble][secondNibble];
    charArray.push(char);
  }
  const relevantText = charArray.filter(
    (_char, i, arr) => arr.findIndex((char) => char === "") > i
  );
  return relevantText.join("");
};
